apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfsmanual
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: 10.107.168.217
